name: Build and deploy Node.js app to Azure Web App - mrstmrecords

on:
  push:
    branches:
      - production-branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        working-directory: ./backend
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend  # 👈 upload the backend folder

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_43A3B5CCB3FC4569BCA4B49AED4D717D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A9EC626FA7EF4285AF2D012B878858E1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D67AD59CE8184A898741AEC8C27C8F13 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mrstmrecords'
          slot-name: 'Production'
          package: ./backend  # 👈 deploy the backend folder


